CONST = 0
UNARY = 1
BINARY = 2
INFIX = 3
LEFTBRACKET = 4,
RIGHTBRACKET = 5
SPACE = 6
UNDEROVER = 7
DEFINITION = 8,
LEFTRIGHT = 9
TEXT = 10
BIG = 11
LONG = 12
STRETCHY = 13,
MATRIX = 14

AMsymbols = [
# some greek symbols
{'input':"alpha",      'tag':"mi", 'output':u"\u03B1", 'ttype':CONST},
{'input':"beta",       'tag':"mi", 'output':u"\u03B2", 'ttype':CONST},
{'input':"chi",        'tag':"mi", 'output':u"\u03C7", 'ttype':CONST},
{'input':"delta",      'tag':"mi", 'output':u"\u03B4", 'ttype':CONST},
{'input':"Delta",      'tag':"mo", 'output':u"\u0394", 'ttype':CONST},
{'input':"epsi",       'tag':"mi", 'output':u"\u03B5", 'ttype':CONST},
{'input':"varepsilon", 'tag':"mi", 'output':u"\u025B", 'ttype':CONST},
{'input':"eta",        'tag':"mi", 'output':u"\u03B7", 'ttype':CONST},
{'input':"gamma",      'tag':"mi", 'output':u"\u03B3", 'ttype':CONST},
{'input':"Gamma",      'tag':"mo", 'output':u"\u0393", 'ttype':CONST},
{'input':"iota",       'tag':"mi", 'output':u"\u03B9", 'ttype':CONST},
{'input':"kappa",      'tag':"mi", 'output':u"\u03BA", 'ttype':CONST},
{'input':"lambda",     'tag':"mi", 'output':u"\u03BB", 'ttype':CONST},
{'input':"Lambda",     'tag':"mo", 'output':u"\u039B", 'ttype':CONST},
{'input':"mu",         'tag':"mi", 'output':u"\u03BC", 'ttype':CONST},
{'input':"nu",         'tag':"mi", 'output':u"\u03BD", 'ttype':CONST},
{'input':"omega",      'tag':"mi", 'output':u"\u03C9", 'ttype':CONST},
{'input':"Omega",      'tag':"mo", 'output':u"\u03A9", 'ttype':CONST},
{'input':"phi",        'tag':"mi", 'output':u"\u03C6", 'ttype':CONST},
{'input':"varphi",     'tag':"mi", 'output':u"\u03D5", 'ttype':CONST},
{'input':"Phi",        'tag':"mo", 'output':u"\u03A6", 'ttype':CONST},
{'input':"pi",         'tag':"mi", 'output':u"\u03C0", 'ttype':CONST},
{'input':"Pi",         'tag':"mo", 'output':u"\u03A0", 'ttype':CONST},
{'input':"psi",        'tag':"mi", 'output':u"\u03C8", 'ttype':CONST},
{'input':"Psi",        'tag':"mi", 'output':u"\u03A8", 'ttype':CONST},
{'input':"rho",        'tag':"mi", 'output':u"\u03C1", 'ttype':CONST},
{'input':"sigma",      'tag':"mi", 'output':u"\u03C3", 'ttype':CONST},
{'input':"Sigma",      'tag':"mo", 'output':u"\u03A3", 'ttype':CONST},
{'input':"tau",        'tag':"mi", 'output':u"\u03C4", 'ttype':CONST},
{'input':"theta",      'tag':"mi", 'output':u"\u03B8", 'ttype':CONST},
{'input':"vartheta",   'tag':"mi", 'output':u"\u03D1", 'ttype':CONST},
{'input':"Theta",      'tag':"mo", 'output':u"\u0398", 'ttype':CONST},
{'input':"upsilon",    'tag':"mi", 'output':u"\u03C5", 'ttype':CONST},
{'input':"xi",         'tag':"mi", 'output':u"\u03BE", 'ttype':CONST},
{'input':"Xi",         'tag':"mo", 'output':u"\u039E", 'ttype':CONST},
{'input':"zeta",       'tag':"mi", 'output':u"\u03B6", 'ttype':CONST},

# binary operation symbols
# {'input':"-",  'tag':"mo", 'output':u"\u0096", 'ttype':CONST},
{'input':"*",        'tag':"mo", 'output':u"\u22C5", 'ttype':CONST},
{'input':"**",       'tag':"mo", 'output':u"\u22C6", 'ttype':CONST},
{'input':"//",       'tag':"mo", 'output':"/",      'ttype':CONST},
{'input':"\\\\",     'tag':"mo", 'output':"\\",     'ttype':CONST},
{'input':"setminus", 'tag':"mo", 'output':"\\",     'ttype':CONST},
{'input':"xx",       'tag':"mo", 'output':u"\u00D7", 'ttype':CONST},
{'input':"xx",       'tag':"mi", 'output':u"\u00D7", 'ttype':CONST},
{'input':"-:",       'tag':"mo", 'output':u"\u00F7", 'ttype':CONST},
{'input':"-:",       'tag':"mi", 'output':u"\u00F7", 'ttype':CONST},
{'input':"-",        'tag':"mo", 'output':u"\u2212", 'ttype':CONST},
{'input':"-",        'tag':"mi", 'output':u"\u2212", 'ttype':CONST},
{'input':"@",        'tag':"mo", 'output':u"\u26AC", 'ttype':CONST},
{'input':"o+",       'tag':"mo", 'output':u"\u2295", 'ttype':CONST},
{'input':"ox",       'tag':"mo", 'output':u"\u2297", 'ttype':CONST},
{'input':"o.",       'tag':"mo", 'output':u"\u2299", 'ttype':CONST},
{'input':"sum",      'tag':"mo", 'output':u"\u2211", 'ttype':UNDEROVER},
{'input':"prod",     'tag':"mo", 'output':u"\u220F", 'ttype':UNDEROVER},
{'input':"^^",       'tag':"mo", 'output':u"\u2227", 'ttype':CONST},
{'input':"^^^",      'tag':"mo", 'output':u"\u22C0", 'ttype':UNDEROVER},
{'input':"vv",       'tag':"mo", 'output':u"\u2228", 'ttype':CONST},
{'input':"vvv",      'tag':"mo", 'output':u"\u22C1", 'ttype':UNDEROVER},
{'input':"nn",       'tag':"mo", 'output':u"\u2229", 'ttype':CONST},
{'input':"nnn",      'tag':"mo", 'output':u"\u22C2", 'ttype':UNDEROVER},
{'input':"uu",       'tag':"mo", 'output':u"\u222A", 'ttype':CONST},
{'input':"uuu",      'tag':"mo", 'output':u"\u22C3", 'ttype':UNDEROVER},

# binary relation symbols
{'input':"!=",   'tag':"mo", 'output':u"\u2260", 'ttype':CONST},
{'input':":=",   'tag':"mo", 'output':":=",     'ttype':CONST},
{'input':"lt",   'tag':"mo", 'output':"<",      'ttype':CONST},
{'input':"<",    'tag':"mo", 'output':"<",      'ttype':CONST},
{'input':"<=",   'tag':"mo", 'output':u"\u2264", 'ttype':CONST},
{'input':"lt=",  'tag':"mo", 'output':u"\u2264", 'ttype':CONST},
{'input':">=",   'tag':"mo", 'output':u"\u2265", 'ttype':CONST},
{'input':"geq",  'tag':"mo", 'output':u"\u2265", 'ttype':CONST},
{'input':"-<",   'tag':"mo", 'output':u"\u227A", 'ttype':CONST},
{'input':"-lt",  'tag':"mo", 'output':u"\u227A", 'ttype':CONST},
{'input':">-",   'tag':"mo", 'output':u"\u227B", 'ttype':CONST},
{'input':"-<=",  'tag':"mo", 'output':u"\u2AAF", 'ttype':CONST},
{'input':">-=",  'tag':"mo", 'output':u"\u2AB0", 'ttype':CONST},
{'input':"in",   'tag':"mo", 'output':u"\u2208", 'ttype':CONST},
{'input':"!in",  'tag':"mo", 'output':u"\u2209", 'ttype':CONST},
{'input':"sub",  'tag':"mo", 'output':u"\u2282", 'ttype':CONST},
{'input':"sup",  'tag':"mo", 'output':u"\u2283", 'ttype':CONST},
{'input':"sube", 'tag':"mo", 'output':u"\u2286", 'ttype':CONST},
{'input':"supe", 'tag':"mo", 'output':u"\u2287", 'ttype':CONST},
{'input':"-=",   'tag':"mo", 'output':u"\u2261", 'ttype':CONST},
{'input':"~=",   'tag':"mo", 'output':u"\u2245", 'ttype':CONST},
{'input':"~~",   'tag':"mo", 'output':u"\u2248", 'ttype':CONST},
{'input':"prop", 'tag':"mo", 'output':u"\u221D", 'ttype':CONST},

# logical symbols
{'input':"and",  'tag':"mtext", 'output':"and",    'ttype':SPACE},
{'input':"or",   'tag':"mtext", 'output':"or",     'ttype':SPACE},
{'input':"not",  'tag':"mo",    'output':u"\u00AC", 'ttype':CONST},
{'input':"=>",   'tag':"mo",    'output':u"\u21D2", 'ttype':CONST},
{'input':"if",   'tag':"mo",    'output':"if",     'ttype':SPACE},
{'input':"<=>",  'tag':"mo",    'output':u"\u21D4", 'ttype':CONST},
{'input':"AA",   'tag':"mo",    'output':u"\u2200", 'ttype':CONST},
{'input':"EE",   'tag':"mo",    'output':u"\u2203", 'ttype':CONST},
{'input':"_|_",  'tag':"mo",    'output':u"\u22A5", 'ttype':CONST},
{'input':"TT",   'tag':"mo",    'output':u"\u22A4", 'ttype':CONST},
{'input':"|--",  'tag':"mo",    'output':u"\u22A2", 'ttype':CONST},
{'input':"|==",  'tag':"mo",    'output':u"\u22A8", 'ttype':CONST},

# grouping brackets
{'input':"(",   'tag':"mo", 'output':"(",      'ttype':LEFTBRACKET},
{'input':")",   'tag':"mo", 'output':")",      'ttype':RIGHTBRACKET},
{'input':"[",   'tag':"mo", 'output':"[",      'ttype':LEFTBRACKET},
{'input':"]",   'tag':"mo", 'output':"]",      'ttype':RIGHTBRACKET},
{'input':"{",   'tag':"mo", 'output':"{",      'ttype':LEFTBRACKET},
{'input':"}",   'tag':"mo", 'output':"}",      'ttype':RIGHTBRACKET},
{'input':"|",   'tag':"mo", 'output':"|",      'ttype':LEFTRIGHT},
#{'input':"||", 'tag':"mo", 'output':"||",     'ttype':LEFTRIGHT},
{'input':"(:",  'tag':"mo", 'output':u"\u2329", 'ttype':LEFTBRACKET},
{'input':":)",  'tag':"mo", 'output':u"\u232A", 'ttype':RIGHTBRACKET},
{'input':"<<",  'tag':"mo", 'output':u"\u2329", 'ttype':LEFTBRACKET},
{'input':">>",  'tag':"mo", 'output':u"\u232A", 'ttype':RIGHTBRACKET},
{'input':"{:",  'tag':"mo", 'output':"{:",     'ttype':LEFTBRACKET},
{'input':":}",  'tag':"mo", 'output':":}",     'ttype':RIGHTBRACKET},

# miscellaneous symbols
{'input':"int",     'tag':"mo", 'output':u"\u222B",  'ttype':CONST},
{'input':"dx",      'tag':"mi", 'output':"{:d x:}", 'ttype':DEFINITION},
{'input':"dy",      'tag':"mi", 'output':"{:d y:}", 'ttype':DEFINITION},
{'input':"dz",      'tag':"mi", 'output':"{:d z:}", 'ttype':DEFINITION},
{'input':"dt",      'tag':"mi", 'output':"{:d t:}", 'ttype':DEFINITION},
{'input':"oint",    'tag':"mo", 'output':u"\u222E",  'ttype':CONST},
{'input':"del",     'tag':"mo", 'output':u"\u2202",  'ttype':CONST},
{'input':"grad",    'tag':"mo", 'output':u"\u2207",  'ttype':CONST},
{'input':"+-",      'tag':"mo", 'output':u"\u00B1",  'ttype':CONST},
{'input':"O/",      'tag':"mo", 'output':u"\u2205",  'ttype':CONST},
{'input':"oo",      'tag':"mo", 'output':u"\u221E",  'ttype':CONST},
{'input':"aleph",   'tag':"mo", 'output':u"\u2135",  'ttype':CONST},
{'input':"...",     'tag':"mo", 'output':"...",     'ttype':CONST},
{'input':":.",      'tag':"mo", 'output':u"\u2234",  'ttype':CONST},
{'input':"/_",      'tag':"mo", 'output':u"\u2220",  'ttype':CONST},
{'input':"\\ ",     'tag':"mo", 'output':u"\u00A0",  'ttype':CONST},
{'input':"quad",    'tag':"mo", 'output':u"\u00A0\u00A0", 'ttype':CONST},
{'input':"qquad",   'tag':"mo", 'output':u"\u00A0\u00A0\u00A0\u00A0", 'ttype':CONST},
{'input':"cdots",   'tag':"mo", 'output':u"\u22EF",  'ttype':CONST},
{'input':"vdots",   'tag':"mo", 'output':u"\u22EE",  'ttype':CONST},
{'input':"ddots",   'tag':"mo", 'output':u"\u22F1",  'ttype':CONST},
{'input':"diamond", 'tag':"mo", 'output':u"\u22C4",  'ttype':CONST},
{'input':"square",  'tag':"mo", 'output':u"\u25A1",  'ttype':CONST},
{'input':"|__",     'tag':"mo", 'output':u"\u230A",  'ttype':CONST},
{'input':"__|",     'tag':"mo", 'output':u"\u230B",  'ttype':CONST},
{'input':"|~",      'tag':"mo", 'output':u"\u2308",  'ttype':CONST},
{'input':"~|",      'tag':"mo", 'output':u"\u2309",  'ttype':CONST},
{'input':"CC",      'tag':"mo", 'output':u"\u2102",  'ttype':CONST},
{'input':"NN",      'tag':"mo", 'output':u"\u2115",  'ttype':CONST},
{'input':"QQ",      'tag':"mo", 'output':u"\u211A",  'ttype':CONST},
{'input':"RR",      'tag':"mo", 'output':u"\u211D",  'ttype':CONST},
{'input':"ZZ",      'tag':"mo", 'output':u"\u2124",  'ttype':CONST},
{'input':"f",       'tag':"mi", 'output':"f",       'ttype':UNARY, 'func':True},
{'input':"g",       'tag':"mi", 'output':"g",       'ttype':UNARY, 'func':True},
{'input':"o",       'tag':"mi", 'output':u"\u00B0",  'ttype':CONST},

# standard functions
{'input':"lim",  'tag':"mo", 'output':"lim",  'ttype':UNDEROVER},
{'input':"Lim",  'tag':"mo", 'output':"Lim",  'ttype':UNDEROVER},
{'input':"sin",  'tag':"mo", 'output':"sin",  'ttype':UNARY, 'func':True},
{'input':"cos",  'tag':"mo", 'output':"cos",  'ttype':UNARY, 'func':True},
{'input':"tan",  'tag':"mo", 'output':"tan",  'ttype':UNARY, 'func':True},
{'input':"sinh", 'tag':"mo", 'output':"sinh", 'ttype':UNARY, 'func':True},
{'input':"cosh", 'tag':"mo", 'output':"cosh", 'ttype':UNARY, 'func':True},
{'input':"tanh", 'tag':"mo", 'output':"tanh", 'ttype':UNARY, 'func':True},
{'input':"cot",  'tag':"mo", 'output':"cot",  'ttype':UNARY, 'func':True},
{'input':"sec",  'tag':"mo", 'output':"sec",  'ttype':UNARY, 'func':True},
{'input':"csc",  'tag':"mo", 'output':"csc",  'ttype':UNARY, 'func':True},
{'input':"log",  'tag':"mo", 'output':"log",  'ttype':UNARY, 'func':True},
{'input':"ln",   'tag':"mo", 'output':"ln",   'ttype':UNARY, 'func':True},
{'input':"det",  'tag':"mo", 'output':"det",  'ttype':UNARY, 'func':True},
{'input':"dim",  'tag':"mo", 'output':"dim",  'ttype':CONST},
{'input':"mod",  'tag':"mo", 'output':"mod",  'ttype':CONST},
{'input':"gcd",  'tag':"mo", 'output':"gcd",  'ttype':UNARY, 'func':True},
{'input':"lcm",  'tag':"mo", 'output':"lcm",  'ttype':UNARY, 'func':True},
{'input':"lub",  'tag':"mo", 'output':"lub",  'ttype':CONST},
{'input':"glb",  'tag':"mo", 'output':"glb",  'ttype':CONST},
{'input':"min",  'tag':"mo", 'output':"min",  'ttype':UNDEROVER},
{'input':"max",  'tag':"mo", 'output':"max",  'ttype':UNDEROVER},

# arrows
{'input':"uarr",   'tag':"mo", 'output':u"\u2191", 'ttype':CONST},
{'input':"darr",   'tag':"mo", 'output':u"\u2193", 'ttype':CONST},
{'input':"rarr",   'tag':"mo", 'output':u"\u2192", 'ttype':CONST},
{'input':"->",     'tag':"mo", 'output':u"\u2192", 'ttype':CONST},
{'input':">->",    'tag':"mo", 'output':u"\u21A3", 'ttype':CONST},
{'input':"->>",    'tag':"mo", 'output':u"\u21A0", 'ttype':CONST},
{'input':">->>",   'tag':"mo", 'output':u"\u2916", 'ttype':CONST},
{'input':"|->",    'tag':"mo", 'output':u"\u21A6", 'ttype':CONST},
{'input':"larr",   'tag':"mo", 'output':u"\u2190", 'ttype':CONST},
{'input':"harr",   'tag':"mo", 'output':u"\u2194", 'ttype':CONST},
# {'input':"rArr",   'tag':"mo", 'output':u"\u21D2", 'ttype':CONST},
{'input':"lArr",   'tag':"mo", 'output':u"\u21D0", 'ttype':CONST},
{'input':"hArr",   'tag':"mo", 'output':u"\u21D4", 'ttype':CONST},
# commands with argument
{'input':"sqrt",      'tag':"msqrt",  'output':"sqrt",     'ttype':UNARY},
{'input':"root",      'tag':"mroot",  'output':"root",     'ttype':BINARY},
{'input':"frac",      'tag':"mfrac",  'output':"/",        'ttype':BINARY},
{'input':"/",         'tag':"mfrac",  'output':"/",        'ttype':INFIX},
{'input':"stackrel",  'tag':"mover",  'output':"stackrel", 'ttype':BINARY},
{'input':"_",         'tag':"msub",   'output':"_",        'ttype':INFIX},
{'input':"^",         'tag':"msup",   'output':"^",        'ttype':INFIX},
{'input':"hat",       'tag':"mover",  'output':u"\u0302",   'ttype':UNARY},
{'input':"hat",       'tag':"mover",  'output':u"\u005E",   'ttype':UNARY},
{'input':"bar",       'tag':"mover",  'output':u"\u00AF",   'ttype':UNARY},
{'input':"vec",       'tag':"mover",  'output':u"\u2192",   'ttype':UNARY},
{'input':"dot",       'tag':"mover",  'output':".",        'ttype':UNARY},
{'input':"dot",       'tag':"mi",     'output':".",        'ttype':UNARY},
{'input':"ddot",      'tag':"mover",  'output':"..",       'ttype':UNARY},
{'input':"ddot",      'tag':"mi",     'output':"..",       'ttype':UNARY},
{'input':"ul",        'tag':"munder", 'output':u"\u0332",   'ttype':UNARY},
{'input':"text",      'tag':"mtext",  'output':"text",     'ttype':TEXT},
{'input':"mbox",      'tag':"mtext",  'output':"mbox",     'ttype':TEXT},
{'input':"\"",        'tag':"mtext",  'output':"mbox",     'ttype':TEXT},
{'input':"bb",        'tag':"mstyle", 'output':"bb",       'ttype':UNARY},
{'input':"mathbf",    'tag':"mstyle", 'output':"mathbf",   'ttype':UNARY},
{'input':"sf",        'tag':"mstyle", 'output':"sf",       'ttype':UNARY},
{'input':"mathsf",    'tag':"mstyle", 'output':"mathsf",   'ttype':UNARY},
{'input':"bbb",       'tag':"mstyle", 'output':"bbb",      'ttype':UNARY},
{'input':"mathbb",    'tag':"mstyle", 'output':"mathbb",   'ttype':UNARY},
{'input':"cc",        'tag':"mstyle", 'output':"cc",       'ttype':UNARY},
{'input':"mathcal",   'tag':"mstyle", 'output':"mathcal",  'ttype':UNARY},
{'input':"tt",        'tag':"mstyle", 'output':"tt",       'ttype':UNARY},
{'input':"mathtt",    'tag':"mstyle", 'output':"mathtt",   'ttype':UNARY},
{'input':"fr",        'tag':"mstyle", 'output':"fr",       'ttype':UNARY},
{'input':"mathfrak",  'tag':"mstyle", 'output':"mathfrak", 'ttype':UNARY}
];

symboltagmap = {}
symbolmap = {}
for symbol in AMsymbols:
    key = (symbol['tag'], symbol['output'])
    symboltagmap[key] = symbol['input']
    symbolmap[symbol['output']] = symbol['input']
